### ISSUE TITLE
Problems Launching on Briss 2.0

### ISSUE THREAD

**Issue by mattlynskey** [mbaeuerle/Briss-2.0#60] opened 2023-01-23 02:27 UTC
Greetings! I am a grateful user of Briss 0.9 for some time. It is a great app. I recently stumbled upon this update when I upgraded to Ventura and Briss 0.9 no longer works. I was very excited to learn about this upgrade! It is such a useful utility!

However, I am having a difficult time installing Briss 2.0. I am at a very, very rudimentary level of technical understanding. I just upgraded to Ventura on my MacOs. When I try to launch the Briss 2.0 file I get the following error (see image below).

This may not be the correct spot to ask for help on the install problems, but I would be grateful for any help in getting this newer version of Briss 2.0 to work on my upgraded MacOs.

Can anyone provide some help?

Thanks in advance! (And thanks for your great work on this utility!)

<img width="249" alt="Screenshot 2023-01-22 at 9 26 20 PM" src="https://user-images.githubusercontent.com/74412970/213956173-ca822223-ca66-4971-821f-413b5536d887.png">

**Comment by mattlynskey** [comment] 2023-01-23 15:49
Greetings! Well, Briss 2.0 is successfully loading at this point. However, when I load a file, it does not finalize the process for the preview. The window just sits at the final step without producing any previews (see image below). Any ideas?

Thanks again for any help you can provide!

<img width="795" alt="Screenshot 2023-01-23 at 10 46 39 AM" src="https://user-images.githubusercontent.com/74412970/214084183-e4488ef5-4252-44d0-b3b5-fa4696b8841a.png">

**Comment by cleydyr** [comment] 2023-01-24 20:30
Hey, @mattlynskey .

Can you share the PDF that is not being loaded successfully by Briss 2.0? Which alpha release of Briss 2.0 exactly are you using?

**Comment by mattlynskey** [comment] 2023-01-24 20:48
Thank you so much for you help @cleydyr! Here is a .pdf where the problem occurs (although, the same issue occurs on multiple .pdfs).

I am using the most recent alpha release **v2.0-alpha-4**.

Thanks for your help!

[10.1515_lingty-2021-0057.pdf](https://github.com/mbaeuerle/Briss-2.0/files/10493885/10.1515_lingty-2021-0057.pdf)

**Comment by cleydyr** [comment] 2023-01-24 21:11
No problem, @mattlynskey .

I can't reproduce the behavior in a MacOS using the document that you've attached. What operating system, processor architecture and Java version are you using?

**Comment by mattlynskey** [comment] 2023-01-25 18:55
I just upgraded to MacOS Ventura 13.1. My processor is 2.3 GHz Quad-Core Intel Core i5.

When I upgraded, Briss 0.9 stopped working. Then, I found Briss 2.0. I tried to use Briss 2.0 but I had the error message in the first post: "The application 'JavaLauncher' can't be opened." I updated Java version 8. I still could not get the program to run (the error message above get coming). A friend helped me run the program through Terminal (maybe this is part of the problem, not sure??). When I run the program, the Briss screen shows up, but any pdf I run does not fully load. I hope this explains the situation.

Thanks so much for your time @cleydyr. Any help you can provide would be greatly appreciated!

**Comment by cleydyr** [comment] 2023-01-25 18:59
Hey, @mattlynskey . I'm also running MacOS Ventura 13.1, but on a M1 Pro processor. And I'm using updated versions of java:

```
$ java -version
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

When you run it through the terminal, is there any error message there when the program gets stuck loading the document?

**Comment by mattlynskey** [comment] 2023-01-25 19:02
Here is what Terminal says as it gets stuck.
[Terminal Saved Output.txt](https://github.com/mbaeuerle/Briss-2.0/files/10502667/Terminal.Saved.Output.txt)

**Comment by mattlynskey** [comment] 2023-01-25 19:03
@cleydyr Could there be a better way to run the program rather than through Terminal? If so, I wonder what the problem is by the original error message: "The application 'JavaLauncher' can't be opened."

**Comment by mattlynskey** [comment] 2023-01-25 19:06
BTW, here is what Terminal says my Java updates are: 

java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

Does anything look off here?

**Comment by cleydyr** [comment] 2023-01-26 08:06
> Could there be a better way to run the program rather than through Terminal?

I don't think this is something we have much control of, as https://github.com/mbaeuerle/Briss-2.0/issues/59 is also about not being able to double click _after upgrading_ the MacOS version. [My comment there](https://github.com/mbaeuerle/Briss-2.0/issues/59#issuecomment-1387322790) may allow you to prescind of the terminal to run Briss 2.0.

It looks like you have a way too updated Java runtime (version 19). We use the JavaFX version 11, which requires Java 10 or 11 according to their [release notes](https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-11.md).

It looks like we'll have to update our JavaFX dependency to allow for use of Java 19. So, for now the workaround is to use a not so recent version of Java, like 17. Or you can wait until we provide support for Java 19.

**Comment by mbaeuerle** [comment] 2023-05-04 19:57
Hey @mattlynskey we just released an updated version which also works for Java 19 and hopefully simplifies things a lot. Give it a try here: https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha-5
Closing this issue for now, but if you still have trouble with this version, let us know!

**Closed by mbaeuerle** 2023-05-04 19:57 UTC

**Comment by mattlynskey** [comment] 2023-05-08 13:29
Thanks @mbaeuerle. I appreciate the update and the continued work on this application. I look forward to working with it!
